default_platform(:ios)

platform :ios do
  desc "Build canary archive and upload to TestFlight"
  lane :testflight_canary do
    profile_path = File.expand_path("~/Library/MobileDevice/Provisioning Profiles/profile.mobileprovision")
    update_project_provisioning(
      xcodeproj: "ios/Runner.xcodeproj",
      profile: profile_path,
      target_filter: "^Runner$",
      build_configuration: "Release-canary",
      code_signing_identity: "Apple Distribution"
    )

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APPSTORE_KEY_ID"),
      issuer_id: ENV.fetch("APPSTORE_ISSUER_ID"),
      key_content: ENV.fetch("APPSTORE_PRIVATE_KEY")
    )
    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "canary",
      configuration: "Release-canary",
      clean: true,
      output_directory: "build/ios/ipa",
      export_method: "app-store",
      codesigning_identity: "Apple Distribution",
      export_options: {
        signingStyle: "manual",
        teamID: ENV.fetch("APPLE_TEAM_ID"),
        signingCertificate: "Apple Distribution",
        provisioningProfiles: {
          "app.fluxer" => ENV.fetch("PROFILE_UUID")
        }
      },
      xcargs: [
        "DEVELOPMENT_TEAM=#{ENV.fetch("APPLE_TEAM_ID")}",
        "CODE_SIGN_STYLE=Manual",
      ].join(" ")
    )
    upload_to_testflight(
      api_key: api_key,
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
      skip_waiting_for_build_processing: true
    )
  end
end
